Repository SnrdTeam/pipeline-tasks, pull requests merged in 2020-12, with the labels that each got.

#3 Check git
  Tasks/CheckGit/.gitignore
  Tasks/CheckGit/icon.png
  Tasks/CheckGit/icon.svg
  Tasks/CheckGit/index.ts
  Tasks/CheckGit/package.json
  Tasks/CheckGit/task.json
  Tasks/CheckGit/tsconfig.json
  Tasks/DownloadSecureFileLegacyV0/package.json
  package-lock.json
  package.json
  vss-extension.json
Labels: enhancement

#5 Hot fix: Add logging, change type input parameter form "bool" to "Boo…
  Tasks/CheckGit/index.ts
  Tasks/CheckGit/task.json
  package-lock.json
  vss-extension.json
Labels: bug, enhancement

#6 Fix detached HEAD trouble
  Tasks/CheckGit/index.ts
  Tasks/CheckGit/task.json
  vss-extension.json
Labels: bug

#7 New CheckGit task icon
  Tasks/CheckGit/icon.png
  Tasks/CheckGit/icon.svg
  Tasks/CheckGit/task.json
  vss-extension.json
Labels: enhancement
